# Main config to direct workflow to user data
# also intending for this to be editable through a GUI later

# I think this config file is mainly unimportant to the general workflow setup and testing
# will only be important if I want an app

# Inputs
counts: "resources/data_small.csv"
meta: "resources/meta.csv"
nf_dds: "resources/nf_dds.dds.Rdata"
formula: "resources/formula.txt"

# Params
# a location for extra parameters with reasonable defaults to fill out later


# Outputs
# output directory seperate from the workflow location
resultsdir: "results"
